package com.junjun.employeeservices.entity;
// Generated Dec 24, 2019 4:27:48 PM by Hibernate Tools 5.1.7.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "jundb")
public class Department implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8341559968157649527L;
	
	private String id;
	private Organization organization;
	private String name;
	private List<Employee> employees = new ArrayList<Employee>();

	public Department() {
	}

	public Department(String id) {
		this.id = id;
	}

	public Department(String id, Organization organization, String name, List<Employee> employees) {
		this.id = id;
		this.organization = organization;
		this.name = name;
		this.employees = employees;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization_id")
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public List<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}
}